import YEAR
a = [
    "GOJOFAN" + YEAR.a,
    "Дед",
    "Дед_макар",
    "ILOVEANIME" + YEAR.a,
    "brff",
    "крипер",
    "сигма",
    "нагибатор" + YEAR.a,
    "valorant",
    "КСер" + YEAR.a,
    "MIRRONAKE",
    "линуксшеф",
    "Я_от_шефа",
    "donk" + YEAR.a,
    "donk666",
    "s1mple" + YEAR.a,
    "s1mple",
    "simple" + YEAR.a,
    "InstagramKiller",
    "ПОСЛАННИК_ФОРУНЫ",
    "FORTUNA_РЕШАЕТ",
    "iloveanime" + YEAR.a,
    "жопич" + YEAR.a,
    "s1A5a8e",
    "GrindBot" + YEAR.a,
    "Лололошка" + YEAR.a,
    "MrLololoshka",
    "lololowka" + YEAR.a,
    "Я_ОТ_ЛИНУКСШЕФА",
    "Shefos_fan" + YEAR.a,
    "Xeon" + YEAR.a,
    "Andrew_devloper",
    "andr123andr",
    "BugKiller" + YEAR.a,
    "MHE_PO_KAJFU",
    "килограмм_пивасика",
    "nedohackers",
    "СЕСТРИШКИН",
    "Cumaпуля",
    "zalupensiya1448",
    "voditel_po_gubam" + YEAR.a,
    "GooningToFemboys",
    "клиторный_потрошитель337",
    "analolizator",
    "аналЛизатор" + YEAR.a,
    "FemboyFriday",
    "етелеком" + YEAR.a,
    "vernitelinuxshefa" + YEAR.a,
    "narezkadetei" + YEAR.a,
    "Xarag",
    "Симпапусик",
    "JDH_FAN",
    "jdh",
    "Windows_user",
    "bro9I" + YEAR.a,
    "fluger",
    "пионер",
    "аквыч",
    "негр",
    "lol",
    # "",
    
]
